-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'POST_LIKE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'POST_COMMENT';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'POST_SHARE';
