export type IndianCity = {
  name: string;
  state?: string;
};

/**
 * Major + tier-2/3 Indian cities used for job/location autocomplete
 * and select dropdowns across web and mobile.
 */
export const INDIAN_CITIES: IndianCity[] = [
  // NCR / Haryana / UP west
  { name: 'Gurugram/Gurgaon', state: 'Haryana' },
  { name: 'Faridabad', state: 'Haryana' },
  { name: 'Panipat', state: 'Haryana' },
  { name: 'Karnal', state: 'Haryana' },
  { name: 'Hisar', state: 'Haryana' },
  { name: 'Rohtak', state: 'Haryana' },
  { name: 'Sonipat', state: 'Haryana' },
  { name: 'Ambala', state: 'Haryana' },
  { name: 'Delhi', state: 'Delhi' },
  { name: 'New Delhi', state: 'Delhi' },
  { name: 'Noida', state: 'Uttar Pradesh' },
  { name: 'Greater Noida', state: 'Uttar Pradesh' },
  { name: 'Ghaziabad', state: 'Uttar Pradesh' },
  { name: 'Lucknow', state: 'Uttar Pradesh' },
  { name: 'Kanpur', state: 'Uttar Pradesh' },
  { name: 'Agra', state: 'Uttar Pradesh' },
  { name: 'Varanasi', state: 'Uttar Pradesh' },
  { name: 'Prayagraj', state: 'Uttar Pradesh' },
  { name: 'Allahabad', state: 'Uttar Pradesh' },
  { name: 'Meerut', state: 'Uttar Pradesh' },
  { name: 'Bareilly', state: 'Uttar Pradesh' },
  { name: 'Aligarh', state: 'Uttar Pradesh' },
  { name: 'Moradabad', state: 'Uttar Pradesh' },
  { name: 'Saharanpur', state: 'Uttar Pradesh' },
  { name: 'Gorakhpur', state: 'Uttar Pradesh' },
  { name: 'Jhansi', state: 'Uttar Pradesh' },
  { name: 'Mathura', state: 'Uttar Pradesh' },
  { name: 'Firozabad', state: 'Uttar Pradesh' },
  { name: 'Muzaffarnagar', state: 'Uttar Pradesh' },

  // Karnataka
  { name: 'Bengaluru', state: 'Karnataka' },
  { name: 'Bangalore', state: 'Karnataka' },
  { name: 'Mysuru', state: 'Karnataka' },
  { name: 'Mysore', state: 'Karnataka' },
  { name: 'Mangaluru', state: 'Karnataka' },
  { name: 'Mangalore', state: 'Karnataka' },
  { name: 'Hubballi', state: 'Karnataka' },
  { name: 'Hubli', state: 'Karnataka' },
  { name: 'Dharwad', state: 'Karnataka' },
  { name: 'Belagavi', state: 'Karnataka' },
  { name: 'Belgaum', state: 'Karnataka' },
  { name: 'Kalaburagi', state: 'Karnataka' },
  { name: 'Gulbarga', state: 'Karnataka' },
  { name: 'Ballari', state: 'Karnataka' },
  { name: 'Bellary', state: 'Karnataka' },
  { name: 'Davangere', state: 'Karnataka' },
  { name: 'Shivamogga', state: 'Karnataka' },
  { name: 'Shimoga', state: 'Karnataka' },
  { name: 'Tumkur', state: 'Karnataka' },
  { name: 'Udupi', state: 'Karnataka' },
  { name: 'Manipal', state: 'Karnataka' },

  // Maharashtra
  { name: 'Mumbai', state: 'Maharashtra' },
  { name: 'Navi Mumbai', state: 'Maharashtra' },
  { name: 'Thane', state: 'Maharashtra' },
  { name: 'Pune', state: 'Maharashtra' },
  { name: 'Nagpur', state: 'Maharashtra' },
  { name: 'Nashik', state: 'Maharashtra' },
  { name: 'Aurangabad', state: 'Maharashtra' },
  { name: 'Chhatrapati Sambhajinagar', state: 'Maharashtra' },
  { name: 'Kolhapur', state: 'Maharashtra' },
  { name: 'Solapur', state: 'Maharashtra' },
  { name: 'Amravati', state: 'Maharashtra' },
  { name: 'Sangli', state: 'Maharashtra' },
  { name: 'Satara', state: 'Maharashtra' },
  { name: 'Jalgaon', state: 'Maharashtra' },
  { name: 'Akola', state: 'Maharashtra' },
  { name: 'Ahmednagar', state: 'Maharashtra' },
  { name: 'Kalyan', state: 'Maharashtra' },
  { name: 'Vasai', state: 'Maharashtra' },
  { name: 'Virar', state: 'Maharashtra' },
  { name: 'Panvel', state: 'Maharashtra' },

  // Telangana / Andhra
  { name: 'Hyderabad', state: 'Telangana' },
  { name: 'Secunderabad', state: 'Telangana' },
  { name: 'Warangal', state: 'Telangana' },
  { name: 'Karimnagar', state: 'Telangana' },
  { name: 'Nizamabad', state: 'Telangana' },
  { name: 'Khammam', state: 'Telangana' },
  { name: 'Visakhapatnam', state: 'Andhra Pradesh' },
  { name: 'Vizag', state: 'Andhra Pradesh' },
  { name: 'Vijayawada', state: 'Andhra Pradesh' },
  { name: 'Guntur', state: 'Andhra Pradesh' },
  { name: 'Nellore', state: 'Andhra Pradesh' },
  { name: 'Tirupati', state: 'Andhra Pradesh' },
  { name: 'Kakinada', state: 'Andhra Pradesh' },
  { name: 'Rajahmundry', state: 'Andhra Pradesh' },
  { name: 'Kurnool', state: 'Andhra Pradesh' },
  { name: 'Anantapur', state: 'Andhra Pradesh' },
  { name: 'Kadapa', state: 'Andhra Pradesh' },
  { name: 'Ongole', state: 'Andhra Pradesh' },
  { name: 'Eluru', state: 'Andhra Pradesh' },

  // Tamil Nadu
  { name: 'Chennai', state: 'Tamil Nadu' },
  { name: 'Coimbatore', state: 'Tamil Nadu' },
  { name: 'Madurai', state: 'Tamil Nadu' },
  { name: 'Tiruchirappalli', state: 'Tamil Nadu' },
  { name: 'Trichy', state: 'Tamil Nadu' },
  { name: 'Salem', state: 'Tamil Nadu' },
  { name: 'Tirunelveli', state: 'Tamil Nadu' },
  { name: 'Erode', state: 'Tamil Nadu' },
  { name: 'Vellore', state: 'Tamil Nadu' },
  { name: 'Thoothukudi', state: 'Tamil Nadu' },
  { name: 'Tuticorin', state: 'Tamil Nadu' },
  { name: 'Thanjavur', state: 'Tamil Nadu' },
  { name: 'Dindigul', state: 'Tamil Nadu' },
  { name: 'Hosur', state: 'Tamil Nadu' },
  { name: 'Nagercoil', state: 'Tamil Nadu' },
  { name: 'Kanchipuram', state: 'Tamil Nadu' },
  { name: 'Karur', state: 'Tamil Nadu' },
  { name: 'Tiruppur', state: 'Tamil Nadu' },

  // Kerala
  { name: 'Kochi', state: 'Kerala' },
  { name: 'Ernakulam', state: 'Kerala' },
  { name: 'Thiruvananthapuram', state: 'Kerala' },
  { name: 'Trivandrum', state: 'Kerala' },
  { name: 'Kozhikode', state: 'Kerala' },
  { name: 'Calicut', state: 'Kerala' },
  { name: 'Thrissur', state: 'Kerala' },
  { name: 'Kannur', state: 'Kerala' },
  { name: 'Kollam', state: 'Kerala' },
  { name: 'Alappuzha', state: 'Kerala' },
  { name: 'Palakkad', state: 'Kerala' },
  { name: 'Kottayam', state: 'Kerala' },
  { name: 'Malappuram', state: 'Kerala' },

  // Gujarat
  { name: 'Ahmedabad', state: 'Gujarat' },
  { name: 'Surat', state: 'Gujarat' },
  { name: 'Vadodara', state: 'Gujarat' },
  { name: 'Rajkot', state: 'Gujarat' },
  { name: 'Gandhinagar', state: 'Gujarat' },
  { name: 'Bhavnagar', state: 'Gujarat' },
  { name: 'Jamnagar', state: 'Gujarat' },
  { name: 'Junagadh', state: 'Gujarat' },
  { name: 'Anand', state: 'Gujarat' },
  { name: 'Morbi', state: 'Gujarat' },
  { name: 'Mehsana', state: 'Gujarat' },
  { name: 'Vapi', state: 'Gujarat' },
  { name: 'Navsari', state: 'Gujarat' },
  { name: 'Bharuch', state: 'Gujarat' },

  // Rajasthan
  { name: 'Jaipur', state: 'Rajasthan' },
  { name: 'Jodhpur', state: 'Rajasthan' },
  { name: 'Udaipur', state: 'Rajasthan' },
  { name: 'Kota', state: 'Rajasthan' },
  { name: 'Ajmer', state: 'Rajasthan' },
  { name: 'Bikaner', state: 'Rajasthan' },
  { name: 'Alwar', state: 'Rajasthan' },
  { name: 'Bhilwara', state: 'Rajasthan' },
  { name: 'Sikar', state: 'Rajasthan' },
  { name: 'Sri Ganganagar', state: 'Rajasthan' },

  // West Bengal / East
  { name: 'Kolkata', state: 'West Bengal' },
  { name: 'Howrah', state: 'West Bengal' },
  { name: 'Durgapur', state: 'West Bengal' },
  { name: 'Asansol', state: 'West Bengal' },
  { name: 'Siliguri', state: 'West Bengal' },
  { name: 'Kharagpur', state: 'West Bengal' },
  { name: 'Haldia', state: 'West Bengal' },
  { name: 'Bhubaneswar', state: 'Odisha' },
  { name: 'Cuttack', state: 'Odisha' },
  { name: 'Rourkela', state: 'Odisha' },
  { name: 'Berhampur', state: 'Odisha' },
  { name: 'Sambalpur', state: 'Odisha' },
  { name: 'Puri', state: 'Odisha' },
  { name: 'Patna', state: 'Bihar' },
  { name: 'Gaya', state: 'Bihar' },
  { name: 'Muzaffarpur', state: 'Bihar' },
  { name: 'Bhagalpur', state: 'Bihar' },
  { name: 'Purnia', state: 'Bihar' },
  { name: 'Ranchi', state: 'Jharkhand' },
  { name: 'Jamshedpur', state: 'Jharkhand' },
  { name: 'Dhanbad', state: 'Jharkhand' },
  { name: 'Bokaro', state: 'Jharkhand' },
  { name: 'Deoghar', state: 'Jharkhand' },

  // Madhya Pradesh / Chhattisgarh
  { name: 'Indore', state: 'Madhya Pradesh' },
  { name: 'Bhopal', state: 'Madhya Pradesh' },
  { name: 'Gwalior', state: 'Madhya Pradesh' },
  { name: 'Jabalpur', state: 'Madhya Pradesh' },
  { name: 'Ujjain', state: 'Madhya Pradesh' },
  { name: 'Sagar', state: 'Madhya Pradesh' },
  { name: 'Rewa', state: 'Madhya Pradesh' },
  { name: 'Satna', state: 'Madhya Pradesh' },
  { name: 'Raipur', state: 'Chhattisgarh' },
  { name: 'Bhilai', state: 'Chhattisgarh' },
  { name: 'Bilaspur', state: 'Chhattisgarh' },
  { name: 'Durg', state: 'Chhattisgarh' },
  { name: 'Korba', state: 'Chhattisgarh' },
  { name: 'Raigarh', state: 'Chhattisgarh' },

  // Punjab / Chandigarh / HP / UK
  { name: 'Chandigarh', state: 'Chandigarh' },
  { name: 'Mohali', state: 'Punjab' },
  { name: 'Ludhiana', state: 'Punjab' },
  { name: 'Amritsar', state: 'Punjab' },
  { name: 'Jalandhar', state: 'Punjab' },
  { name: 'Patiala', state: 'Punjab' },
  { name: 'Bathinda', state: 'Punjab' },
  { name: 'Pathankot', state: 'Punjab' },
  { name: 'Hoshiarpur', state: 'Punjab' },
  { name: 'Panchkula', state: 'Haryana' },
  { name: 'Shimla', state: 'Himachal Pradesh' },
  { name: 'Dharamshala', state: 'Himachal Pradesh' },
  { name: 'Mandi', state: 'Himachal Pradesh' },
  { name: 'Solan', state: 'Himachal Pradesh' },
  { name: 'Dehradun', state: 'Uttarakhand' },
  { name: 'Haridwar', state: 'Uttarakhand' },
  { name: 'Rishikesh', state: 'Uttarakhand' },
  { name: 'Haldwani', state: 'Uttarakhand' },
  { name: 'Roorkee', state: 'Uttarakhand' },
  { name: 'Nainital', state: 'Uttarakhand' },

  // Northeast + Goa + J&K / Ladakh
  { name: 'Guwahati', state: 'Assam' },
  { name: 'Dibrugarh', state: 'Assam' },
  { name: 'Silchar', state: 'Assam' },
  { name: 'Jorhat', state: 'Assam' },
  { name: 'Shillong', state: 'Meghalaya' },
  { name: 'Imphal', state: 'Manipur' },
  { name: 'Aizawl', state: 'Mizoram' },
  { name: 'Agartala', state: 'Tripura' },
  { name: 'Kohima', state: 'Nagaland' },
  { name: 'Dimapur', state: 'Nagaland' },
  { name: 'Itanagar', state: 'Arunachal Pradesh' },
  { name: 'Gangtok', state: 'Sikkim' },
  { name: 'Panaji', state: 'Goa' },
  { name: 'Margao', state: 'Goa' },
  { name: 'Vasco da Gama', state: 'Goa' },
  { name: 'Mapusa', state: 'Goa' },
  { name: 'Srinagar', state: 'Jammu and Kashmir' },
  { name: 'Jammu', state: 'Jammu and Kashmir' },
  { name: 'Leh', state: 'Ladakh' },
  { name: 'Puducherry', state: 'Puducherry' },
  { name: 'Pondicherry', state: 'Puducherry' },
  { name: 'Port Blair', state: 'Andaman and Nicobar Islands' },

  // Work modes
  { name: 'Remote' },
  { name: 'Work from home' },
  { name: 'Hybrid' },
];

/** Sorted unique city names for select dropdowns. */
export const INDIAN_CITY_OPTIONS = Array.from(
  new Set(INDIAN_CITIES.map((city) => city.name)),
).sort((a, b) => a.localeCompare(b));
